modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="player_tracking"
version="${file.jarVersion}"
displayName="Player Tracking"
logoFile="player_tracking.png"
credits=""
authors="Biggest_Xuan"
description='''
'''
[[dependencies.player_tracking]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.player_tracking]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
